### ISSUE TITLE
CyberThreat Intelligence Team Almaviva - esselunga.it.txt file removal

### ISSUE THREAD

**Issue by cyberthreat-almaviva** [rix4uni/EmailFinder#1]
Hi,
We are the Cybersecurity Team Almaviva Group, on behalf of one of our clients, Esselunga, we would like to request the removal of the following email file:

- https://github.com/rix4uni/EmailFinder/blob/88b1d50b8cef63b886f77d78eaeb90847999f950/Emails/esselunga.it.txt

**Comment by rix4uni** [comment]
Deleted:
- https://github.com/rix4uni/EmailFinder/blob/main/Emails/esselunga.it.txt

**Comment by cyberthreat-almaviva** [comment]
Email addresses are still available at the following address: https://github.com/rix4uni/EmailFinder/blob/88b1d50b8cef63b886f77d78eaeb90847999f950/Emails/esselunga.it.txt

We kindly request the removal of this blob.

**Comment by rix4uni** [comment]
I deleted all latest commit from past 2 months, now no one will able to see this file and these emails, expect you and me because i and you know this blob commit id, if you close this issue know one know this commit id even exist including you and me.

I checked my self all commit and i'm unable to find this file `esselunga.it.txt`, you can verify using these commands:
```
git clone https://github.com/rix4uni/EmailFinder.git
git -C EmailFinder/ --no-pager log --pretty=format:%H | xargs -I{} git -C EmailFinder/ --no-pager show {} | grep "esselunga.it.txt"
```
